version: "3"
services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    depends_on: 
      - artifactory
    volumes:
      - "$HOME/Volumes/jenkins_home:/var/jenkins_home"
    ports:
      - "8080:8080"
      - "50000:50000"
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss
    volumes:
      - "$HOME/Volumes/artifactory:/var/opt/jfrog/artifactory"
    ports: 
      - "8081:8081"